Quotation_Index:
    path:  /quotation/index/{family}
    controller: App\Controller\QuotationController::index
    defaults:
        family: null

Quotation_listDatatables:
    path:  /listquotationdatatables
    controller: App\Controller\QuotationController::listQuotationDatatables

Quotation_Read:
    path:  /quotation/read/{id}
    controller: App\Controller\QuotationController::readQuotation
    requirements:
        id: \d+

Humor_Read:
    path:  /humor/read/{id}
    controller: App\Controller\QuotationController::readHumor
    requirements:
        id: \d+

Humor_listDatatables:
    path:  /listhumordatatables
    controller: App\Controller\QuotationController::listHumorDatatables

Lyric_Read:
    path:  /lyric/read/{id}
    controller: App\Controller\QuotationController::readLyric
    requirements:
        id: \d+

Lyric_listDatatables:
    path:  /listlyricdatatables
    controller: App\Controller\QuotationController::listLyricDatatables

Proverb_listDatatables:
    path:  /listproverbdatatables
    controller: App\Controller\QuotationController::listProverbDatatables

Saying_listDatatables:
    path:  /listsayingdatatables
    controller: App\Controller\QuotationController::listSayingDatatables

Proverb_Country_Show:
    path:  /quotation/proverb/{id}/{title}
    controller: App\Controller\QuotationController::proverbCountry
    requirements:
        id: \d+

Proverb_listProverbByCountryDatatables:
    path:  /listproverbbycountrydatatables/{countryId}
    controller: App\Controller\QuotationController::listProverbByCountryDatatables
    requirements:
        countryId: \d+

Proverb_Read:
    path:  /proverb/read/{id}
    controller: App\Controller\QuotationController::readProverb
    requirements:
        id: \d+

Saying_Read:
    path:  /saying/read/{id}
    controller: App\Controller\QuotationController::readSaying
    requirements:
        id: \d+

Saying_Country_Show:
    path:  /quotation/saying/{id}/{title}
    controller: App\Controller\QuotationController::sayingCountry
    requirements:
        id: \d+

Saying_listSayingByCountryDatatables:
    path:  /listsayingbycountrydatatables/{countryId}
    controller: App\Controller\QuotationController::listSayingByCountryDatatables
    requirements:
        countryId: \d+

Poem_listDatatables:
    path:  /listpoemdatatables
    controller: App\Controller\QuotationController::listPoemDatatables

Poem_Read:
    path:  /poem/read/{id}
    controller: App\Controller\QuotationController::readPoem
    requirements:
        id: \d+

Quotation_quotationsServerSide:
    path:  /quotation_server_side/{authorId}/{page}
    controller: App\Controller\QuotationController::quotationsServerSide
    defaults:
        page: 1
    requirements:
        authorId: \d+

Biography_Index:
    path: /biography
    controller: App\Controller\BiographyController::indexAction

Biography_Show:
    path: /biography/{id}/{title_slug}
    controller: App\Controller\BiographyController::readAction
    defaults:
        title_slug: null
    requirements:
        id: \d+

Biography_ListDatatables:
    path: /biograpgy/listdatatables
    controller: App\Controller\BiographyController::listDatatablesAction

Biography_World:
    path: /biography/world/{language}
    controller: App\Controller\BiographyController::worldAction
    defaults:
        language: all
    requirements:
        theme: ".+"

Biography_WorldDatatables:
    path: /biography/worlddatatables/{language}
    controller: App\Controller\BiographyController::worldDatatablesAction
    defaults:
        language: all

# Administration
Quotation_Admin:
    resource: "routing/quotationadmin.yml"
    prefix:   /admin/quotation

Biography_Admin:
    resource: "routing/biographyadmin.yml"
    prefix:   /admin/biography