Quotation_ListQuotation:
    path:  /quotation/{family}
    controller: App\Controller\QuotationController::listQuotationAction

Quotation_listQuotationDatatables:
    path:  /listquotationdatatables/{family}
    controller: App\Controller\QuotationController::listQuotationDatatablesAction

Quotation_ReadQuotation:
    path:  /quotation/read/{id}
    controller: App\Controller\QuotationController::readQuotationAction
    requirements:
        id: \d+

Proverb_Country_Show:
    path:  /quotation/proverb/{id}/{title}
    controller: App\Controller\QuotationController::proverbCountryAction
    requirements:
        id: \d+

Proverb_listProverbByCountryDatatables:
    path:  /listproverbbycountrydatatables/{countryId}
    controller: App\Controller\QuotationController::listProverbByCountryDatatablesAction
    requirements:
        countryId: \d+

Quotation_quotationsServerSide:
    path:  /quotation_server_side/{authorId}/{page}
    controller: App\Controller\QuotationController::quotationsServerSideAction
    defaults:
        page: 1
    requirements:
        authorId: \d+

Biography_Index:
    path: /biography
    controller: App\Controller\BiographyController::indexAction

Biography_Show:
    path: /biography/{id}/{title}
    controller: App\Controller\BiographyController::readAction
    defaults:
        title: null
    requirements:
        id: \d+

Biography_ListDatatables:
    path: /biograpgy/listdatatables
    controller: App\Controller\BiographyController::listDatatablesAction

Biography_World:
    path: /biography/world/{language}
    controller: App\Controller\BiographyController::worldAction
    defaults:
        language: all
    requirements:
        theme: ".+"

Biography_WorldDatatables:
    path: /biography/worlddatatables/{language}
    controller: App\Controller\BiographyController::worldDatatablesAction
    defaults:
        language: all

# Administration
Quotation_Admin:
    resource: "routing/quotationadmin.yml"
    prefix:   /admin/quotation

Biography_Admin:
    resource: "routing/biographyadmin.yml"
    prefix:   /admin/biography