<?php
namespace App\Service;

class AI
{
	public function gemini($text, $format, $locale)
	{
		// https://aistudio.google.com/apikey
		$apiKey = $_ENV["GOOGLE_GEMINI_AI_APIKEY"];

		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		$message = "Language: $locale - write a message for $format about: $text";

		curl_setopt($ch, CURLOPT_URL, "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$apiKey");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"contents\": [{\n    \"parts\":[{\"text\": \"$message\"}]\n    }]\n   }");

		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

		$headers = array();
		$headers[] = 'Content-Type: application/json';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
		
		return json_decode($result)->candidates[0]->content->parts[0]->text;
	}
}