<?php
namespace App\Service;

class AI
{
	public function gemini($text, $format, $locale)
	{
		// https://aistudio.google.com/apikey
		$apiKey = $_ENV["GOOGLE_GEMINI_AI_APIKEY"];
		
		$error = false;
		$result = null;

		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();
		
		$text = str_replace('"', "", $text);

		$message = "Language: $locale - write a message for $format about: $text";

		curl_setopt($ch, CURLOPT_URL, "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$apiKey");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"contents\": [{\n    \"parts\":[{\"text\": \"$message\"}]\n    }]\n   }");

		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

		$headers = array();
		$headers[] = 'Content-Type: application/json';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			$result = curl_error($ch);
			$error = true;
		}
		curl_close($ch);
		
		if($error)
			return ["error" => $error, "result" => $result];

		return ["error" => $error, "message" => trim(json_decode($result)->candidates[0]->content->parts[0]->text, '"')];
	}

	public function cerebras($text, $format, $locale) {
		$apiKey = "csk-fd8mednjwp3hrfvwk5exhmyk54m32vdjwn98k5trm8k4694k";

		$error = false;
		$result = null;

		$text = str_replace('"', "", $text);

		$message = "Language: $locale - write a message for $format about: $text";

		$data = [
			'model' => 'llama3.1-8b',
			'max_completion_tokens' => 1024,
			'temperature' => 0.2,
			'top_p' => 1,
			'stream' => false,
			'messages' => [
				[
					'role' => 'user',
					'content' => $message
				]
			]
		];

		$ch = curl_init('https://api.cerebras.ai/v1/chat/completions');

		curl_setopt_array($ch, [
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_POST           => true,
			CURLOPT_HTTPHEADER     => [
				'Content-Type: application/json',
				'Authorization: Bearer ' . $apiKey,
			],
			CURLOPT_POSTFIELDS     => json_encode($data),
		]);

		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

		$result = curl_exec($ch);
		$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

		if (curl_errno($ch)) {
			$error = true;
			$result = curl_error($ch);
		}

		curl_close($ch);
		
		if($error) {
			return ["error" => $error, "result" => $result];
		}
		
		$result = json_decode($result, true);
		
		return ["error" => $error, "message" => $result["choices"][0]["message"]["content"]];
	}
}