doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.default
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                IF: App\DQL\IfElse
                GROUP_CONCAT: App\DQL\GroupConcat
                IFNULL: App\DQL\IfNull
                JSON_SEARCH: App\DQL\JsonSearch
                JSON_CONTAINS: App\DQL\JsonContains
                JSON_EXTRACT: App\DQL\JsonExtract
                LPAD: App\DQL\Lpad
                REGEXP: App\DQL\Regexp
                EXTRACT: App\DQL\Extract