ap_tags_index:
    path:  /tags/index
    controller: App\Controller\TagsController::index

ap_tags_ListDatatables:
    path: /tags/listdatatables
    controller: App\Controller\TagsController::listDatatables

ap_tags_search:
    path:  /searchtags/{id}/{title_slug}
    controller: App\Controller\TagsController::search
    defaults:
        title_slug: null

ap_tags_searchdatatables:
    path:  /searchtagsdatatables/{id}/{title}
    controller: App\Controller\TagsController::searchDatatablesAction

ap_tags_tagsavailableedit:
    path:  /tagsavailableedit
    controller: App\Controller\TagsController::TagsAvailableEditAction

# Administration
TagWord_Admin:
    resource: "routing/tagwordadmin.yml"
    prefix:   /admin/tagword