APCommentBundle_homepage:
    path:  /comment/{idClassName}/{className}
    controller: App\Controller\CommentController::indexAction

APCommentBundle_create:
    path:  /comment/create/{idClassName}/{className}
    controller: App\Controller\CommentController::createAction

APCommentBundle_reply:
    path:  /comment/reply/{idClassName}/{className}
    controller: App\Controller\CommentController::reply

APCommentBundle_pagination:
    path:  /comment/pagination/{idClassName}/{className}
    controller: App\Controller\CommentController::paginationAction

apcomment_admin:
    resource: "routing/commentadmin.yml"
    prefix:   /admin/comment