Page_About:
    path:  /about
    controller: App\Controller\PageController::aboutAction

Page_Copyright:
    path:  /copyright
    controller: App\Controller\PageController::copyrightAction

Page_Faq:
    path:  /faq
    controller: App\Controller\PageController::faqAction

Page_PrivacyPolicy:
    path:  /privacy-policy
    controller: App\Controller\PageController::privacyPolicyAction

# Page_Cookie:
    # path: /cookie
    # controller: App\Controller\PageController::cookieAction

Page_IndexRSSFeed:
    path:  /rss
    controller: App\Controller\PageController::indexRSSFeedAction

Page_GenerateRSSFeed:
    path:  /rssfeed
    controller: App\Controller\PageController::generateRSSFeedAction

Page_Cryptocurrency:
    path:  /cryptocurrency/{title}
    controller: App\Controller\PageController::cryptocurrency

Page_Generic:
    path:  /{internationalName}
    controller: App\Controller\PageController::getPageByInternationalNameAction

President_Archive_Index:
    path: /wordpresident/index
    controller: App\Controller\PageController::wordPresidentArchiveAction

President_Archive_Read:
    path: /wordpresident/read/{id}
    controller: App\Controller\PageController::wordPresidentReadArchiveAction

EventMessage_Read:
    path: /event/read/{id}/{title_slug}
    controller: App\Controller\EventMessageController::readAction
    defaults:
        title_slug: null

EventMessage_Tab:
    path:  /event/tab/{id}/{theme}
    controller: App\Controller\EventMessageController::tabAction
    requirements:
        theme: ".+"

EventMessage_TabDatatables:
    path: /tabdatatables/{themeId}
    controller: App\Controller\EventMessageController::tabDatatablesAction

EventMessage_Calendar:
    path: /event/calendar
    controller: App\Controller\EventMessageController::calendarAction

EventMessage_Calendar_Events:
    path: /event/calendar/loadevents
    controller: App\Controller\EventMessageController::calendarLoadEventsAction

EventMessage_New:
    path: /event/new
    controller: App\Controller\EventMessageController::newAction

EventMessage_Create:
    path: /event/create
    controller: App\Controller\EventMessageController::createAction

EventMessage_Edit:
    path: /event/edit/{id}
    controller: App\Controller\EventMessageController::editAction

EventMessage_Update:
    path: /event/update/{id}
    controller: App\Controller\EventMessageController::createAction

EventMessage_Waiting:
    path: /event/waiting/{id}
    controller: App\Controller\EventMessageController::waitingAction

EventMessage_Validate:
    path: /event/validate/{id}
    controller: App\Controller\EventMessageController::validateAction

EventMessage_World:
    path: /event/world/{language}/{themeId}/{theme}
    controller: App\Controller\EventMessageController::worldAction
    defaults:
        language: all
        themeId: 0
        theme: null
    requirements:
        theme: ".+"

EventMessage_WorldDatatables:
    path: /event/worlddatatables/{language}/{themeId}
    controller: App\Controller\EventMessageController::worldDatatablesAction
    defaults:
        language: all
        themeId: 0

EventMessage_SelectThemeForIndexWorld:
    path: /event/selectThemeForIndexWorldAction/{language}
    controller: App\Controller\EventMessageController::selectThemeForIndexWorldAction
    defaults:
        language: all

EventMessage_SelectDayMonth:
    path: /event/day_month/{year}/{month}/{day}
    controller: App\Controller\EventMessageController::getAllEventsByDayAndMonthAction

EventMessage_SelectYearMonth:
    path: /event/year_month/{year}/{month}
    controller: App\Controller\EventMessageController::getAllEventsByYearOrMonthAction

EventMessage_SelectYear:
    path: /event/year/{year}
    controller: App\Controller\EventMessageController::getAllEventsByYearAction

# Administration
President_Admin:
    resource: "routing/presidentadmin.yml"
    prefix:   /admin/president

Page_Admin:
    resource: "routing/pageadmin.yml"
    prefix: /admin/page

EventMessage_Admin:
    resource: "routing/eventmessageadmin.yml"
    prefix: /admin/eventmessage