# Administration
UsefulLink_Admin:
    resource: "routing/usefullinkadmin.yml"
    prefix:   /admin/usefullink

KnowledgeBase_Admin:
    resource: "routing/knowledgebaseadmin.yml"
    prefix:   /admin/knowledgebase

UsefullinkTags_Admin:
    resource: "routing/usefullinktagsadmin.yml"
    prefix:   /admin/usefullinktags