UsefulLink_Index:
    path:  /usefullink/{page}/{tag}
    controller: App\Controller\UsefulLinkController::index
    defaults:
        page: 1
        tag: null
    requirements:
       page: \d+

UsefulLink_Read:
    path:  /usefullink/read/{id}
    controller: App\Controller\UsefulLinkController::read

UsefulLink_Counter:
    path:  /usefullink/counter
    controller: App\Controller\UsefulLinkController::counter

# Administration
UsefulLink_Admin:
    resource: "routing/usefullinkadmin.yml"
    prefix:   /admin/usefullink

KnowledgeBase_Admin:
    resource: "routing/knowledgebaseadmin.yml"
    prefix:   /admin/knowledgebase