UsefulLink_Index:
    path:  /usefullink/{page}
    controller: App\Controller\UsefulLinkController::indexAction
    defaults:
        page: 1
    requirements:
       page: \d+

# Administration
UsefulLink_Admin:
    resource: "routing/usefullinkadmin.yml"
    prefix:   /admin/usefullink

KnowledgeBase_Admin:
    resource: "routing/knowledgebaseadmin.yml"
    prefix:   /admin/knowledgebase