Admin_Index:
    path:  /admin/index
    controller: App\Controller\AdminController::indexAction

Admin_SelectLanguage:
    path:  /admin/selectLanguage/{language}
    controller: App\Controller\AdminController::selectLanguageAction
    defaults:
        language: "fr"

Admin_Phpinfo:
    path: /admin/phpinfo
    controller: App\Controller\AdminController::phpinfoAction

Admin_Mastodon:
    path: /admin/mastodon/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::mastodonAction

Admin_Facebook:
    path: /admin/facebook/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::facebookAction

Admin_VK:
    path: /admin/vk/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::vk

Admin_Instagram:
    path: /admin/instagram/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::instagramAction

Admin_TheDailyTruth:
    path: /admin/thedailytruth/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::thedailytruthAction

Admin_Blogger:
    path: /admin/blogger/{id}/{path}/{routeToRedirect}/{type}/{method}
    controller: App\Controller\AdminController::bloggerAction
    defaults:
        type: "test"
        method: "POST"

Admin_BloggerPost:
    path: /admin/bloggerpost
    controller: App\Controller\AdminController::bloggerPostAction

Admin_Diaspora:
    path: /admin/diaspora/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::diasporaAction
    defaults:
        method: "POST"

Admin_DiasporaPost:
    path: /admin/diasporapost
    controller: App\Controller\AdminController::diasporaPostAction

Admin_BloggerTags:
    path: /admin/bloggertags/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::bloggerTagsAction

Admin_Shopify:
    path: /admin/shopify/{id}/{path}/{routeToRedirect}/{type}
    controller: App\Controller\AdminController::shopifyAction

Admin_ShopifyPost:
    path: /admin/shopifypost
    controller: App\Controller\AdminController::shopifyPostAction

Admin_Twitter:
    path: /admin/twitter/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::twitterAction

Admin_TwitterMastodon:
    path: /admin/twittermastodon/{id}/{path}/{routeToRedirect}/{socialNetwork}
    controller: App\Controller\AdminController::twitterMastodonAction

Admin_Pinterest:
    path: /admin/pinterest/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::pinterestAction

Admin_Tumblr:
    path: /admin/tumblr/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::tumblrAction

Admin_TumblrPost:
    path: /admin/tumblrpost
    controller: App\Controller\AdminController::tumblrPostAction

Admin_WikipediaSections:
    path: /admin/loadWikipediaSectionsPageAction
    controller: App\Controller\AdminController::loadWikipediaSectionsPageAction

Admin_ImportWikipedia:
    path: /admin/import
    controller: App\Controller\AdminController::importWikipediaAction

Admin_Muse:
    path: /admin/muse/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::museAction

Admin_WakondaGuru:
    path: /admin/wakonda_guru/{id}/{path}/{routeToRedirect}
    controller: App\Controller\AdminController::wakondaGuruAction

Admin_WikidataGeneric:
    path: /admin/wikidata_generic
    controller: App\Controller\AdminController::wikidataGenericAction

Admin_WikidataGenericLoadImage:
    path: /admin/wikidata_generic_load_image
    controller: App\Controller\AdminController::wikidataGenericLoadImageAction

Admin_Maintenance:
    path: /admin/maintenance/{mode}
    controller: App\Controller\AdminController::maintenanceAction
    defaults:
        mode: ""

Admin_SQLExplorer:
    path: /admin/sqlExplorer
    controller: App\Controller\AdminController::sqlExplorer

Admin_Sitemap:
    path: /admin/sitemap
    controller: App\Controller\AdminController::generateSitemap

# Backup
Backup_Admin_Index:
    path: /admin/backup/index
    controller: App\Controller\BackupAdminController::indexAction

Backup_Admin_Delete:
    path: /admin/backup/delete/{filename}
    controller: App\Controller\BackupAdminController::deleteAction

Backup_Admin_Download:
    path: /admin/backup/download/{filename}
    controller: App\Controller\BackupAdminController::downloadAction

Backup_Admin_Generate:
    path: /admin/backup/generate
    controller: App\Controller\BackupAdminController::generateAction