<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

use App\Entity\Biography;
use App\Entity\EntityLinkBiography;

/**
 * BiographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiographyRepository extends MappedSuperclassBaseRepository
{
	public function countBiography($locale)
	{
		$qb = $this->createQueryBuilder('c');

		$qb->select("count(c)")
			->join('c.language', 'l')
			->where('l.abbreviation = :locale')
			->setParameter('locale', $locale);

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function getBiographies($locale)
	{
		$qb = $this->createQueryBuilder('c');

		$qb	->join('c.language', 'l')
			->where('l.abbreviation = :locale')
			->setParameter('locale', $locale);

		return $qb->getQuery()->getResult();
	}
	
	public function getDatatablesForIndex($locale, $iDisplayStart, $iDisplayLength, $sortByColumn, $sortDirColumn, $sSearch, $datas = [], $count = false)
	{
		$qb = $this->createQueryBuilder('c');

		$aColumns = array( 'c.title', 'c.title');

		$qb->join('c.language', 'l')
		   ->where('l.abbreviation = :locale')
		   ->setParameter('locale', $locale);

		if(!empty($title = $datas["title"])) {
			$search = "%".$title."%";
			$qb->andWhere('c.title LIKE :search')
			   ->setParameter('search', $search);
		}

		if(!empty($occupation = $datas["occupation"])) {
			$qb->join(EntityLinkBiography::class, "elb", \Doctrine\ORM\Query\Expr\Join::WITH, "elb.biography = c.id")
			   ->andWhere('elb.occupation = :occupation')
			   ->setParameter('occupation', $occupation);
		}
		if(!empty($country = $datas["country"])) {
			$qb->join("c.nationality", "co")
			   ->andWhere('co.internationalName = :abbreviation')
			   ->setParameter('abbreviation', $country->getInternationalName());
		}
		
		if(!empty($sortDirColumn))
		   $qb->orderBy($aColumns[$sortByColumn[0]], $sortDirColumn[0]);
		
		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";
			$qb->andWhere('c.title LIKE :search')
			   ->setParameter('search', $search);
		}
		if($count)
		{
			$qb->select("count(c)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		return $qb->getQuery()->getResult();
	}

	// ADMINISTRATION
	public function countAdmin()
	{
		$qb = $this->createQueryBuilder('c');
		$qb->select("count(c)");

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function getDatatablesForIndexAdmin($iDisplayStart, $iDisplayLength, $sortByColumn, $sortDirColumn, $sSearch, $searchByColumns, $toComplete = null, $count = false)
	{
		$aColumns = array( 'c.id', 'c.title', 'l.title', 'c.id');

		$qb = $this->createQueryBuilder('c');
		$qb->join('c.language', 'l')
		   ->orderBy($aColumns[$sortByColumn[0]], $sortDirColumn[0]);

		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";
			foreach($aColumns as $column)
			{
				$qb->orWhere($column." LIKE :search")
				   ->setParameter('search', $search);
			}
		}
		
		if(!empty($toComplete)) {
			switch($toComplete) {
				case "textToComplete":
					$qb->andWhere("c.text IS NULL");
					break;
				case "imageToComplete":
					$qb->andWhere("c.illustration IS NULL");
					break;
				case "birthDateToComplete":
					$qb->andWhere("c.birthDate IS NULL");
					break;
				case "deathDateToComplete":
					$qb->andWhere("c.deathDate IS NULL");
					break;
				case "nationalityToComplete":
					$qb->andWhere("c.nationality IS NULL");
					break;
			}
		}

		if($count)
		{
			$qb->select("count(c)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		return $qb->getQuery()->getResult();
	}

	public function countForDoublons($entity)
	{
		$qb = $this->createQueryBuilder("b");
		$qb->select("count(b)")
		   ->where("b.title = :title")
		   ->setParameter("title", $entity->getTitle())
		   ->innerjoin("b.language", "l")
		   ->andWhere("l.abbreviation = :abbreviation")
		   ->setParameter("abbreviation", $entity->getLanguage()->getAbbreviation());
		   
		if($entity->getId() != null)
		{
		   $qb->andWhere("b.id != :id")
		      ->setParameter("id", $entity->getId());
		}
		
		return $qb->getQuery()->getSingleScalarResult();
	}

	public function getBiographyInCorrectLanguage($entity, $locale)
	{
		$qb = $this->createQueryBuilder("b");
		$qb->leftjoin("b.language", "l")
		   ->where("l.abbreviation = :locale")
		   ->setParameter("locale", $locale)
		   ->andWhere("b.internationalName = :internationalName")
		   ->setParameter("internationalName", $entity->getInternationalName());
		   
		return $qb->getQuery()->getOneOrNullResult();
	}
	
	// FORM
	public function getBiographyByLanguage($language)
	{
		$qb = $this->createQueryBuilder('li');
		$qb->join('li.language', 'l')
		   ->where('l.abbreviation = :lang')
		   ->setParameter('lang', $language)
		   ->orderBy('li.title');

		return $qb;
	}

	public function getBiographiesByLanguagesAndInternationalName($languages, $internationalName)
	{
		$qb = $this->createQueryBuilder('bi');
		
		$qb->select('l.abbreviation AS abbr, bi.title AS title, l.logo AS logo, bi.id AS id')
		   ->leftjoin('bi.language', 'l')
		   ->where('bi.internationalName = :internationalName')
		   ->setParameter('internationalName', $internationalName);

		return $qb->getQuery()->getResult(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY);
	}
	
	public function getFileSelectorColorboxAdmin($iDisplayStart, $iDisplayLength, $sSearch, $count = false)
	{
		$qb = $this->createQueryBuilder('c');
		$qb->orderBy('c.internationalName', 'DESC')
		   ->join("c.illustration", "il")
		   ->where("il.realNameFile IS NOT NULL");

		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";

			$qb->andWhere("il.titleFile LIKE :search")
			   ->setParameter('search', $search);
		}
		if($count)
		{
			$qb->select("COUNT(DISTINCT il.realNameFile)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->groupBy('il.realNameFile')->orderBy("c.id", "DESC")->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		$entities = $qb->getQuery()->getResult();
		$res = array();
		
		foreach($entities as $entity)
		{
			$photo = new \StdClass();
			$photo->photo = $entity->getIllustration()->getTitleFile();
			$photo->path = $entity->getAssetImagePath();
			
			$res[] = $photo;
		}
		
		return $res;
	}

	public function getDatatablesForWorldIndex($language, $iDisplayStart, $iDisplayLength, $sortByColumn, $sortDirColumn, $sSearch, $count = false)
	{
		$qb = $this->createQueryBuilder('c');

		$aColumns = array( 'l.abbreviation', 'il.titleFile', 'c.title');
		
		$qb->join('c.language', 'l')
		   ->leftjoin("c.illustration", "il");

		if($language == "all")
		{
			$currentLanguages = $this->currentLanguages;
			$whereIn = array();
			for($i = 0; $i < count($currentLanguages); $i++)
			{
				$whereIn[] = ':'.$currentLanguages[$i];
				$qb->setParameter(':'.$currentLanguages[$i], $currentLanguages[$i]);
			}

			$qb->andWhere('l.abbreviation NOT IN ('.implode(", ", $whereIn).')');
		}
		else
		{
			$qb->andWhere('l.abbreviation = :language');
			$qb->setParameter('language', $language);
		}
		
		if(!empty($sortDirColumn))
		   $qb->orderBy($aColumns[$sortByColumn[0]], $sortDirColumn[0]);
		
		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";
			$qb->andWhere('c.title LIKE :search')
			   ->setParameter('search', $search);
		}
		if($count)
		{
			$qb->select("count(c)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		return $qb->getQuery()->getResult();
	}
	
	public function getAutocomplete($locale, $query)
	{
		$qb = $this->createQueryBuilder("b");
		
		$qb->select("MAX(b.title) AS title")
		   ->addSelect("MAX(b.birthDate) AS birthDate")
		   ->addSelect("b.id AS id")
		   ->addSelect("MAX(b.deathDate) AS deathDate")
		   ->addSelect("GROUP_CONCAT(l.title SEPARATOR '#') AS languages")
		   ->addSelect("b.internationalName")
		   ->addSelect("b.wikidata")
		   ->join("b.language", "l")
		   ->groupBy("b.internationalName")
		   ->addGroupBy("b.wikidata");
		
		if(!empty($locale))
		{
			$qb
			   ->leftjoin("b.language", "la")
			   ->where('la.abbreviation = :locale')
			   ->setParameter('locale', $locale);
		}
		   
		if(!empty($query))
		{
			$query = is_array($query) ? "%".$query[0]."%" : "%".$query."%";
			$query = "%".$query."%";
			$qb->andWhere("b.title LIKE :query")
			   ->setParameter("query", $query);
		}
		
		$qb->andWhere("b.kind = :person")
		   ->setParameter("person", Biography::PERSON);
		
		$qb->orderBy("b.title", "ASC")
		   ->setMaxResults(15);

		return $qb->getQuery()->getResult();
	}
	
	public function getBiographyByWikidataOrTitle(string $title, string $wikidata)
	{
		if(empty($title) and empty($wikidata))
			return [];

		$qb = $this->createQueryBuilder("b");
		
		$qb->select("MAX(b.title) AS title")
		   ->addSelect("MAX(b.birthDate) AS birthDate")
		   ->addSelect("MAX(b.deathDate) AS deathDate")
		   ->addSelect("GROUP_CONCAT(l.title SEPARATOR '#') AS languages")
		   ->addSelect("i.realNameFile AS illustration")
		   ->addSelect("b.internationalName")
		   ->addSelect("b.wikidata")
		   ->addSelect("n.title AS nationality")
		   ->join("b.language", "l")
		   ->leftjoin("b.illustration", "i")
		   ->leftjoin("b.nationality", "n")
		   ->groupBy("b.internationalName")
		   ->addGroupBy("b.wikidata");
		   
		if(!empty($title))
			$qb->where("b.title = :title")
		       ->setParameter("title", $title);
		   
		if(!empty($wikidata))
			$qb->orWhere("b.wikidata = :wikidata")
		       ->setParameter("wikidata", $wikidata);

		return $qb->getQuery()->getResult();
	}
}