<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookVoteRepository extends VoteRepository
{
}