<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookCommentRepository extends CommentRepository
{
}