<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CartographyCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartographyCommentRepository extends CommentRepository
{
}