<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CreepyStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreepyStoryRepository extends MappedSuperclassBaseRepository
{
	public function countCreepyStory($lang)
	{
		$qb = $this->createQueryBuilder('c');
		$qb->select("count(c)")
			->join('c.language', 'o')
			->where('o.abbreviation = :lang')
			->join('c.state', 's')
			->andWhere('s.displayState = 1')
			->setParameter('lang', $lang)
			->andWhere("c.archive = false");

		return $qb->getQuery()->getSingleScalarResult();
	}
	
	public function nbrByTheme($lang, $theme)
	{
		$qb = $this->createQueryBuilder('o');
		$qb->select("count(o)")
			->join('o.language', 'c')
			->join('o.theme', 't')
			->where('c.abbreviation = :lang')
			->setParameter('lang', $lang)
			->andWhere('t.title = :theme')
			->join('o.state', 's')
			->setParameter('theme', $theme)
			->andWhere("o.archive = false");

		return $qb->getQuery()->getSingleScalarResult();	
	}



	public function getAllCreepyStoryByThemeAndLanguage($language)
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select("SUM(if( s.displayState = 1 AND o.archive = false, 1, 0)) AS total")
		   ->addSelect("t.title")
		   ->addSelect("t.id")
		   ->addSelect("pt.title AS parentTheme")
		   ->from("\App\Entity\Theme", "t")
		   ->leftjoin(\App\Entity\CreepyStory::class, "o", \Doctrine\ORM\Query\Expr\Join::WITH, "o.theme = t.id")
		   ->leftjoin("o.state", "s")
		   ->leftjoin('t.language', 'l')
		   ->leftjoin('t.parentTheme', 'pt')
		   ->where('l.abbreviation = :language')
		   ->setParameter('language', $language)
		   ->andWhere("t.parentTheme IS NOT NULL")
		   ->groupby("t.title")
		   ->orderBy("t.title");

		return $qb->getQuery()->getResult();
	}




	public function getTab($themeId, $lang, $iDisplayStart, $iDisplayLength, $sortByColumn, $sortDirColumn, $sSearch, $count = false)
	{
		$qb = $this->createQueryBuilder('o');

		$aColumns = array('il.titleFile','o.title', 'o.publicationDate');

		$qb->join('o.language', 'c')
		   ->join('o.theme', 't')
		   ->join("o.illustration", "il")
		   ->where('t.id = :themeId')
		   ->setParameter('themeId', $themeId)
		   ->andWhere('c.abbreviation = :lang')
		   ->setParameter('lang', $lang)
		   ->join('o.state', 's')
		   ->andWhere('s.displayState = 1')
		   ->orderBy('o.publicationDate')
		   ->andWhere("o.archive = false");

		if(!empty($sortDirColumn))
		   $qb->orderBy($aColumns[$sortByColumn[0]], $sortDirColumn[0]);
		
		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";
			$qb->andWhere('o.title LIKE :search')
			   ->setParameter('search', $search);
		}
		if($count)
		{
			$qb->select("count(o)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		return $qb->getQuery()->getResult();
	}

	public function getPreviousAndNextEntities($entity, $language)
	{
		$qb = $this->createQueryBuilder('n');
		$qb->orderBy('n.publicationDate', 'DESC')->orderBy('n.id', 'DESC')
		   ->where('n.publicationDate <= :publicationDate')
		   ->andWhere('n.id != '.$entity->getId())
		   ->setParameter('publicationDate', $entity->getPublicationDate())
		   ->join('n.language', 'l')
		   ->andWhere('l.abbreviation = :language')
		   ->andWhere("n.archive = false")
		   ->setParameter('language', $language)
		   ->setMaxResults(1);

		$previousEntity = $qb->getQuery()->getOneOrNullResult();

		$qb = $this->createQueryBuilder('n');
		$qb->orderBy('n.publicationDate', 'DESC')->orderBy('n.id', 'ASC')
		   ->where('n.publicationDate >= :publicationDate')->andWhere('n.id != '.$entity->getId())
		   ->setParameter('publicationDate', $entity->getPublicationDate())
		   ->join('n.language', 'l')
		   ->andWhere('l.abbreviation = :language')
		   ->setParameter('language', $language)
		   ->andWhere("n.archive = false")
		   ->setMaxResults(1);

		$nextEntity = $qb->getQuery()->getOneOrNullResult();

		return array("previous" => $previousEntity, "next" => $nextEntity);
	}
	
	public function getSameTopics($entity)
	{
		$qb = $this->createQueryBuilder('c');
		$qb->join('c.language', 'l')
		   ->join('c.state', 's')
		   ->where('l.abbreviation = :lang')
		   ->setParameter('lang', $entity->getLanguage()->getAbbreviation())
		   ->andWhere('s.displayState = 1')
		   ->andWhere("c.id != :id")
		   ->setParameter("id", $entity->getId())
		   ->join('c.theme', 'o')
	       ->andWhere('o.id = :themeId')
		   ->setParameter('themeId', $entity->getTheme()->getId())
		   ->andWhere("c.archive = false")
		   ->orderBy('c.publicationDate', 'desc')
		   ->setMaxResults(3);

		return $qb->getQuery()->getResult();
	}

	// ADMINISTRATION
	public function countAdmin()
	{
		$qb = $this->createQueryBuilder('c');
		$qb->select("count(c)");

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function getDatatablesForIndexAdmin($iDisplayStart, $iDisplayLength, $sortByColumn, $sortDirColumn, $sSearch, $searchByColumns, $count = false)
	{
		$aColumns = array( 'c.id', 'c.title', 'c.publicationDate', 'c.id');

		$qb = $this->createQueryBuilder('c');
		$qb->orderBy($aColumns[$sortByColumn[0]], $sortDirColumn[0]);

		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";
			$orWhere = [];
			
			foreach($aColumns as $column)
				$orWhere[] = $column." LIKE :search";

			$qb->andWhere(implode(" OR ", $orWhere))
			   ->setParameter('search', $search);
		}
		if($count)
		{
			$qb->select("count(c)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		return $qb->getQuery()->getResult();
	}
	
	public function getFileSelectorColorboxAdmin($iDisplayStart, $iDisplayLength, $sSearch, $count = false)
	{
		return $this->getFileSelectorColorboxIllustrationAdmin($iDisplayStart, $iDisplayLength, $sSearch, $count);
	}

	public function getRandom($locale)
	{
		$qb = $this->createQueryBuilder("o");

		$qb->select("COUNT(o) AS countRow")
		   ->join('o.language', 'l')
		   ->join('o.state', 's')
		   ->where('l.abbreviation = :locale')
		   ->andWhere('o.archive = false')
		   ->andWhere('s.displayState = 1')
		   ->setParameter('locale', $locale);
		
		$max = max($qb->getQuery()->getSingleScalarResult() - 1, 0);
		$offset = rand(0, $max);

		$qb = $this->createQueryBuilder("o");

		$qb->join('o.language', 'l')
		   ->join('o.state', 's')
		   ->where('l.abbreviation = :locale')
		   ->andWhere('o.archive = false')
		   ->andWhere('s.displayState = 1')
		   ->setParameter('locale', $locale)
		   ->setFirstResult($offset)
		   ->setMaxResults(1);

		return $qb->getQuery()->getOneOrNullResult();
	}
}