<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentCommentRepository extends CommentRepository
{
}