<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntityLinkBiography
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityLinkBiographyRepository extends EntityRepository
{
	public function getOccupationsByBiography($biography): ?array
	{
		$qb = $this->createQueryBuilder("mb");
		
		$qb->select("GROUP_CONCAT(mb.occupation SEPARATOR '|') AS occupations")
		   ->where("mb.biography = :biography")
		   ->setParameter("biography", $biography)
		   ->groupBy("mb.biography")
		   ->setMaxResults(1);
		   
		return !empty($result = $qb->getQuery()->getOneOrNullResult()) ? array_unique(explode("|", $result["occupations"])) : [];
	}
}