<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventMessageVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventMessageVoteRepository extends VoteRepository
{
}