<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FileManagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileManagementRepository extends EntityRepository
{
}