<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrimoireCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrimoireCommentRepository extends CommentRepository
{
}