<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrimoireVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrimoireVoteRepository extends VoteRepository
{
}