<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieBiography
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieBiographyRepository extends EntityRepository
{
	public function getMovieByBiography($biography)
	{
		$qb = $this->createQueryBuilder("mb");
		
		$qb->select("m.title AS movieTitle, m.slug AS movieSlug, mb.role AS movieRole, m.id AS movieId, g.title AS genreTitle, g.id AS genreId, GROUP_CONCAT(mb.occupation SEPARATOR '|') AS occupations")
		   ->where("mb.biography = :biography")
		   ->setParameter("biography", $biography)
		   ->join("mb.movie", "m")
		   ->join("m.genre", "g")
		   ->groupBy("mb.movie")
		   ->addGroupBy("mb.biography");
		   
		return $qb->getQuery()->getResult();
	}
}