<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieVoteRepository extends VoteRepository
{
}