<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieCommentRepository extends CommentRepository
{
}