<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MusicBiographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicBiographyRepository extends EntityRepository
{
	public function getMusicsByBiography($biography)
	{
		$qb = $this->createQueryBuilder("mb");

		$qb->select("m.musicPiece AS musicTitle, m.id AS musicId, GROUP_CONCAT(mb.occupation SEPARATOR '|') AS occupations")
		   ->where("mb.biography = :biography")
		   ->setParameter("biography", $biography)
		   ->join("mb.music", "m")
		   ->groupBy("mb.music")
		   ->addGroupBy("mb.biography");

		return $qb->getQuery()->getResult();
	}

	public function getBiographiesByMusic($music)
	{
		$qb = $this->createQueryBuilder("mb");
		
		$qb->select("b.id AS biographyId, b.title AS biographyTitle, b.slug AS biographySlug, IFNULL(mb.role, b.title) AS stageName, m.id AS musicId")
		   ->addSelect("GROUP_CONCAT(DISTINCT mb.occupation SEPARATOR '#') AS occupations")
		   ->where("mb.music = :music")
		   ->setParameter("music", $music)
		   ->join("mb.music", "m")
		   ->join("mb.biography", "b")
		   ->groupBy("b.title");
		   
		$datas = [];

		foreach($qb->getQuery()->getResult() as $res) {
			$res["occupations"] = explode("#", $res["occupations"]);
			$datas[] = $res;
		}

		return $datas;
	}
}