<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsVoteRepository extends VoteRepository
{
	public function getAverageVotesByArticle($entity)
	{
		$qb = $this->createQueryBuilder("v");
		$qb->select('AVG(v.valueVote) AS ratingAverage')
		   ->where('v.entity = :entityId')
		   ->setParameter('entityId', $entity->getId());
	   
		$result = $qb->getQuery()->getSingleResult();

		if(!is_array($result) or empty($result['ratingAverage']))
			return '-';
		
		return $result['ratingAverage'];
	}
}