<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsCommentRepository extends CommentRepository
{
}