<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsVoteRepository extends VoteRepository
{
}