<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PresidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresidentRepository extends EntityRepository
{
	public function getPresidentAdmin()
	{
		$qb = $this->createQueryBuilder('c');

		return $qb->getQuery()->getResult();
	}

	public function getPresidentIndex($language)
	{
		$qbCount = $this->createQueryBuilder('o');

		$qbCount->select('COUNT(o)')
		        ->join('o.language', 'l')
			    ->where('l.abbreviation = :lang')
			    ->setParameter('lang', $language)
				->andWhere("o.logo IS NOT NULL");

		$max = max($qbCount->getQuery()->getSingleScalarResult() - 1, 0);
		$offset = rand(0, $max);

		$qb = $this->createQueryBuilder('c');
		$qb->join('c.language', 'l')
		   ->where('l.abbreviation = :lang')
		   ->setParameter('lang', $language)
		   ->andWhere("CURRENT_DATE() BETWEEN c.publicationDate AND DATE_ADD(c.publicationDate, c.numberOfDays, 'day')")
		   ->orderBy("c.publicationDate", "DESC")
		   ->andWhere("c.logo IS NOT NULL")
		   ->setFirstResult($offset)
		   ->setMaxResults(1);

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function getPresidentsIndex($language)
	{
		$qb = $this->createQueryBuilder('c');
		$qb->join('c.language', 'l')
		   ->where('l.abbreviation = :lang')
		   ->setParameter('lang', $language)
		   ->andWhere("CURRENT_DATE() BETWEEN c.publicationDate AND DATE_ADD(c.publicationDate, c.numberOfDays, 'day')")
		   ->orderBy("c.publicationDate", "DESC");

		return $qb->getQuery()->getResult();
	}
	
	public function getPresidentArchive($language)
	{
		$qb = $this->createQueryBuilder('c');
		$qb->join('c.language', 'l')
		   ->where('l.abbreviation = :lang')
		   ->setParameter('lang', $language)
		   ->orderBy("c.publicationDate", "DESC");

		return $qb->getQuery()->getResult();
	}

	// ADMINISTRATION
	public function countAdmin()
	{
		$qb = $this->createQueryBuilder('c');
		$qb->select("count(c)");

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function getDatatablesForIndexAdmin($iDisplayStart, $iDisplayLength, $sortByColumn, $sortDirColumn, $sSearch, $searchByColumns, $count = false)
	{
		$aColumns = array( 'c.id', 'c.title', 'l.title', 'c.id');

		$qb = $this->createQueryBuilder('c');
		$qb->join('c.language', 'l')
		   ->orderBy($aColumns[$sortByColumn[0]], $sortDirColumn[0]);

		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";
			$orWhere = [];
			
			foreach($aColumns as $column)
				$orWhere[] = $column." LIKE :search";

			$qb->andWhere(implode(" OR ", $orWhere))
			   ->setParameter('search', $search);
		}
		if($count)
		{
			$qb->select("count(c)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		return $qb->getQuery()->getResult();
	}
	
	public function getFileSelectorColorboxAdmin($iDisplayStart, $iDisplayLength, $sSearch, $count = false)
	{
		return $this->getFileSelectorColorboxIllustrationAdmin($iDisplayStart, $iDisplayLength, $sSearch, $count);
	}
}