<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationRepository extends EntityRepository
{
	public function countCitation($lang)
	{
		$qb = $this->createQueryBuilder('c');

		$qb->select("count(c)")
			->join('c.language', 'l')
			->where('l.abbreviation = :lang')
			->setParameter('lang', $lang);

		return $qb->getQuery()->getSingleScalarResult();
	}
	
	public function listeCitation($lang)
	{	
		$queryBuilder = $this->createQueryBuilder('o');

		$queryBuilder->join('o.language', 'l')
					->where('l.abbreviation = :lang')
					->setParameter('lang', $lang)
					->orderBy('o.textQuotation');

		return $queryBuilder->getQuery()->getResult();
	}	
	
	public function randomQuote($lang)
	{
		$qbCount = $this->createQueryBuilder('o');

		$qbCount->select('COUNT(o)')
		        ->join('o.language', 'l')
			    ->where('l.abbreviation = :lang')
			    ->setParameter('lang', $lang);

		$max = max($qbCount->getQuery()->getSingleScalarResult() - 1, 0);
		$offset = rand(0, $max);

		$qb = $this->createQueryBuilder('o');

		$qb ->join('o.language', 'l')
			->where('l.abbreviation = :lang')
			->setParameter('lang', $lang)
			->setFirstResult($offset)
			->setMaxResults(1);
		
		return $qb->getQuery()->getOneOrNullResult();
	}

	public function getDatatablesForIndex($iDisplayStart, $iDisplayLength, $sortByColumn, $sortDirColumn, $sSearch, $language, $count = false)
	{
		$aColumns = array('c.textQuotation', 'a.title');

		$qb = $this->createQueryBuilder('c');
		$qb->join('c.language', 'l')
		   ->join('c.authorQuotation', 'a')
		   ->where('l.abbreviation = :language')
		   ->setParameter('language', $language)
		   ->orderBy($aColumns[$sortByColumn[0]], $sortDirColumn[0]);

		$query = array();
		   
		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";
			foreach($aColumns as $column)
			{
				$query[] = $column." LIKE :search";
				$qb->setParameter('search', $search);
			}
			$qb->andWhere(implode(" OR ", $query));
		}
		if($count)
		{
			$qb->select("count(c)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		return $qb->getQuery()->getResult();
	}

	// ADMINISTRATION
	public function countAdmin()
	{
		$qb = $this->createQueryBuilder('c');

		$qb->select("count(c)");

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function getDatatablesForIndexAdmin($iDisplayStart, $iDisplayLength, $sortByColumn, $sortDirColumn, $sSearch, $searchByColumns, $count = false)
	{
		$aColumns = array( 'c.id', 'a.title', 'c.textQuotation', 'l.title', 'c.id');

		$qb = $this->createQueryBuilder('c');
		$qb->join('c.language', 'l')
		   ->join('c.authorQuotation', 'a')
		   ->orderBy($aColumns[$sortByColumn[0]], $sortDirColumn[0]);

		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";
			foreach($aColumns as $column)
			{
				$qb->orWhere($column." LIKE :search")
				   ->setParameter('search', $search);
			}
		}
		if($count)
		{
			$qb->select("count(c)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		return $qb->getQuery()->getResult();
	}

	public function countForDoublons($entity)
	{
		if(is_null($entity->getAuthorQuotation()) or is_null($entity->getLanguage()))
			return 0;

		$qb = $this->createQueryBuilder("b");
		$qb->select("count(b)")
		   ->where("b.textQuotation = :textQuotation")
		   ->setParameter("textQuotation", $entity->getTextQuotation())
		   ->innerjoin("b.language", "l")
		   ->andWhere("l.abbreviation = :abbreviation")
		   ->setParameter("abbreviation", $entity->getLanguage()->getAbbreviation())
		   ->innerjoin("b.authorQuotation", "a")
		   ->andWhere("a.title = :authorQuotation")
		   ->setParameter("authorQuotation", $entity->getAuthorQuotation()->getTitle());
		   
		if($entity->getId() != null)
		{
		   $qb->andWhere("b.id != :id")
		      ->setParameter("id", $entity->getId());
		}
		
		return $qb->getQuery()->getSingleScalarResult();
	}
	
	public function getQuotationsByAuthor($biography, $language)
	{
		$queryBuilder = $this->createQueryBuilder('o');
		
		$queryBuilder->join('o.authorQuotation', 'b')
					->join('o.language', 'l')
					->where('l.abbreviation = :language')
					->setParameter('language', $language)
					->andWhere('b.id = :biography')
					->setParameter('biography', $biography->getId())
					->orderBy('o.id', 'DESC');

		return $queryBuilder->getQuery();
	}
}