<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuotationImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationImageRepository extends EntityRepository
{
}