<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TelevisionSerieCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelevisionSerieCommentRepository extends CommentRepository
{
}