<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TelevisionSerieVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelevisionSerieVoteRepository extends VoteRepository
{
}