<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TelevisionSerieBiography
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelevisionSerieBiographyRepository extends EntityRepository
{
	public function getTelevisionSerieByBiography($biography)
	{
		$qb = $this->createQueryBuilder("mb");
		
		$qb->select("m.title AS televisionSerieTitle, m.slug AS televisionSerieSlug, mb.role AS televisionSerieRole, m.id AS televisionSerieId, g.title AS genreTitle, g.id AS genreId, GROUP_CONCAT(mb.occupation SEPARATOR '|') AS occupations")
		   ->where("mb.biography = :biography")
		   ->setParameter("biography", $biography)
		   ->join("mb.televisionSerie", "m")
		   ->join("m.genre", "g")
		   ->groupBy("mb.televisionSerie")
		   ->addGroupBy("mb.biography");
		   
		$res = $qb->getQuery()->getResult();
		
		$qb = $this->createQueryBuilder("mb");
		
		$qb->select("m.title AS televisionSerieTitle, m.slug AS televisionSerieSlug, mb.role AS televisionSerieRole, m.id AS televisionSerieId, g.title AS genreTitle, g.id AS genreId, GROUP_CONCAT(mb.occupation SEPARATOR '|') AS occupations")
		   ->where("mb.biography = :biography")
		   ->setParameter("biography", $biography)
		   ->join("mb.episodeTelevisionSerie", "et")
		   ->join("et.televisionSerie", "m")
		   ->join("m.genre", "g")
		   ->groupBy("mb.episodeTelevisionSerie")
		   ->addGroupBy("mb.biography");
		   
		return array_merge($res, $qb->getQuery()->getResult());
	}
}