<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TestimonyFileManagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonyFileManagementRepository extends EntityRepository
{
	public function getAllFilesForTestimonyByIdClassName($idClassName, $kind = null)
	{
		$qb = $this->createQueryBuilder('o');

		$qb->join('o.testimony', 'a')
			->where('a.id = :idClassComment')
			->setParameter('idClassComment', $idClassName);
			
		if(!empty($kind)) {
			$qb->andWhere('o.kindFile = :kind')
			   ->setParameter('kind', $kind);
		}

		return $qb->getQuery()->getResult();
	}
}