<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsefulLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsefulLinkRepository extends EntityRepository
{
	public function getUsefulLLinks($category, $page, $locale) {
		$qb = $this->createQueryBuilder("c");
		
		$qb->join("c.language", "l")
		   ->where("l.abbreviation = :locale")
		   ->setParameter("locale", $locale)
		   ->andWhere("c.category = :category")
		   ->setParameter("category", $category);
		   
		return $qb->getQuery();
	}
	
	public function countAdmin()
	{
		$qb = $this->createQueryBuilder('c');
		$qb->select("count(c)");

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function getDatatablesForIndexAdmin($iDisplayStart, $iDisplayLength, $sortByColumn, $sortDirColumn, $sSearch, $searchByColumns, $filter = null, $count = false)
	{
		$aColumns = array( 'c.id', 'c.title', 'c.category', 'c.links', 'c.id');

		$qb = $this->createQueryBuilder('c');
		$qb->orderBy($aColumns[$sortByColumn[0]], $sortDirColumn[0]);

		if(!empty($sSearch))
		{
			$search = "%".$sSearch."%";
			foreach($aColumns as $column)
			{
				$qb->orWhere($column." LIKE :search")
				   ->setParameter('search', $search);
			}
		}

		if(!empty($filter)) {
			if(isset($filter["category_filter"]) and !empty($value = $filter["category_filter"])) {
				$qb->andWhere("c.category = :valueCategory")
				   ->setParameter("valueCategory", $value);
			}
			if(isset($filter["tags_filter"]) and !empty($value = $filter["tags_filter"])) {
				$qb->andWhere("JSON_CONTAINS(JSON_EXTRACT(LOWER(c.tags), '$[*].value'), LOWER('\"".$value."\"'), '$') = true");
			}
		}
		
		if($count)
		{
			$qb->select("count(c)");
			return $qb->getQuery()->getSingleScalarResult();
		}
		else
			$qb->setFirstResult($iDisplayStart)->setMaxResults($iDisplayLength);

		return $qb->getQuery()->getResult();
	}
}
