<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoCommentRepository extends CommentRepository
{
}