<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
	public function averageVote($className, $idClassName)
	{	
		$qb = $this->createQueryBuilder('o');

		$qb ->select('avg(o.valueVote)')
			->where('o.classNameVote = :classNameVote')
			->setParameter('classNameVote', $className)
			->andWhere('o.idClassVote = :idClassVote')
			->setParameter('idClassVote', $idClassName);

		return $qb->getQuery()->getSingleScalarResult();
	}
	
	public function countVoteByClassName($className, $idClassName)
	{	
		$qb = $this->createQueryBuilder('c');

		$qb ->select('count(c.valueVote)')
			->where('c.classNameVote = :classNameVote')
			->setParameter('classNameVote', $className)
			->andWhere('c.idClassVote = :idClassVote')
			->setParameter('idClassVote', $idClassName);

		return $qb->getQuery()->getSingleScalarResult();
	}
}