<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WitchCraftCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WitchcraftToolCommentRepository extends CommentRepository
{
}