Photo_Index:
    path:  /photo
    controller: App\Controller\PhotoController::indexAction

Photo_TabPicture:
    path:  /photo/tab/{id}/{theme}
    controller: App\Controller\PhotoController::tabPictureAction
    requirements:
        theme: ".+"

Photo_TabPictureDatatables:
    path: /photo/tabpicturedatatables/{themeId}
    controller: App\Controller\PhotoController::tabPictureDatatablesAction

Photo_Read:
    path: /photo/read/{id}/{title_slug}
    controller: App\Controller\PhotoController::readAction
    defaults:
        title_slug: null

Photo_Pdfversion:
    path: /photo/pdfversion/{id}
    controller: App\Controller\PhotoController::pdfVersionAction

Photo_World:
    path: /photo/world/{language}/{themeId}/{theme}
    controller: App\Controller\PhotoController::worldAction
    defaults:
        language: all
        themeId: 0
        theme: null
    requirements:
        theme: ".+"

Photo_WorldDatatables:
    path: /photo/worlddatatables/{language}/{themeId}
    controller: App\Controller\PhotoController::worldDatatablesAction
    defaults:
        language: all
        themeId: 0

Photo_SelectThemeForIndexWorld:
    path: /photo/selectThemeForIndexWorldAction/{language}
    controller: App\Controller\PhotoController::selectThemeForIndexWorldAction
    defaults:
        language: all

Photo_New:
    path: /photo/new
    controller: App\Controller\PhotoController::newAction

Photo_Create:
    path: /photo/create
    controller: App\Controller\PhotoController::createAction

Photo_Edit:
    path: /photo/edit/{id}
    controller: App\Controller\PhotoController::editAction

Photo_Update:
    path: /photo/update/{id}
    controller: App\Controller\PhotoController::createAction

Photo_Validate:
    path: /photo/validate/{id}
    controller: App\Controller\PhotoController::validateAction

# Administration
Photo_Admin:
    resource: "routing/photoadmin.yml"
    prefix:   /admin/photo