Vote_Index:
    path:  /vote/{className}/{idClassName}
    controller: App\Controller\VoteController::indexAction

Vote_Edit:
    path:  /vote/edit/{idClassName}/{className}
    controller: App\Controller\VoteController::editAction

Vote_ListVoteBtUser:
    path:  /vote/list/user/{authorId}
    controller: App\Controller\VoteController::listVoteByUser

Vote_ListVoteByUserDatatables:
    path:  /listVoteByUserDatatables/{authorId}
    controller: App\Controller\VoteController::listVoteByUserDatatables