Store_Index:
    path: /store/{page}
    controller: App\Controller\StoreController::indexAction
    defaults:
        page: 1
    requirements:
        page: \d+

Store_Show:
    path: /store/{id}/{title_slug}
    controller: App\Controller\StoreController::showAction
    defaults:
        title_slug: null
    requirements:
        id: \d+

Store_Random:
    path: /store/random
    controller: App\Controller\StoreController::randomAction

# Administration
Store_Admin:
    resource: "routing/storeadmin.yml"
    prefix:   /admin/store