FileManagement_Index:
    path:  /filemanagement/{idClassName}/{className}
    controller: App\Controller\FileManagementController::indexAction
    requirements:
       idClassName: \d+

FileManagement_Create:
    path:  /filemanagement/create/{idClassName}/{className}
    controller: App\Controller\FileManagementController::createAction

FileManagement_Delete:
    path:  /filemanagement/delete
    controller: App\Controller\FileManagementController::deleteAction

FileManagement_Uploadfile:
    path:  /filemanagement/uploadfile/{idClassName}/{className}
    controller: App\Controller\FileManagementController::uploadFileAction
    requirements:
       idClassName: \d+

FileManagement_UploadfileDropzone:
    path:  /filemanagement/uploadfiledropzone/{idClassName}/{className}
    controller: App\Controller\FileManagementController::uploadFileDropzoneAction
    requirements:
       idClassName: \d+

FileManagement_UploadFileWysiwyg:
    path:  /filemanagement/uploadfilewysiwyg/{pathFile}
    controller: App\Controller\FileManagementController::uploadFileWysiwygAction

FileManagement_SaveImagePaint:
    path: /filemanagement/saveImagePaint/{idClassName}/{className}
    controller: App\Controller\FileManagementController::saveImagePaintAction

FileManagement_Download:
    path: /filemanagement/download/{id}/{path}/{folder}
    controller: App\Controller\FileManagementController::downloadAction
    defaults:
        folder: public
    requirements:
       id: \d+

FileManagement_DisplayImage:
    path: /filemanagement/displayImage
    controller: App\Controller\FileManagementController::displayImage

# Administration
FileManagement_Admin:
    resource: "routing/filemanagementadmin.yml"
    prefix:   /admin/filemanagement