# Administration
Banner_Admin:
    resource: "routing/banneradmin.yml"
    prefix:   /admin/banner

Region_Admin:
    resource: "routing/regionadmin.yml"
    prefix:   /admin/region

Language_Admin:
    resource: "routing/languageadmin.yml"
    prefix:   /admin/language

Licence_Admin:
    resource: "routing/licenceadmin.yml"
    prefix:   /admin/licence

Theme_Admin:
    resource: "routing/themeadmin.yml"
    prefix:   /admin/theme

State_Admin:
    resource: "routing/stateadmin.yml"
    prefix:   /admin/state