# News and Archive
ap_newsmobile_index:
    path:  /mobile/index/{page}/{theme}
    controller: App\Controller\NewsMobileController::indexAction
    defaults:
        theme: null
    requirements:
       page: \d+
       theme: ".+"

ap_newsmobile_selectthemeforindexnew:
    path: /mobile/selectThemeForIndexNew
    controller: App\Controller\NewsMobileController::selectThemeForIndexNewAction

ap_videomobile_index:
    path:  /mobile/video/{page}/{theme}
    controller: App\Controller\VideoMobileController::indexAction
    defaults:
        theme: null
    requirements:
       page: \d+
       theme: ".+"

ap_videomobile_selectthemeforindex:
    path: /mobile/video/selectThemeForIndex
    controller: App\Controller\VideoMobileController::selectThemeForIndexNewAction

ap_videomobile_read:
    path:  /mobile/video/read/{id}
    controller: App\Controller\VideoMobileController::readAction
    requirements:
       id: \d+

ap_newsmobile_read:
    path:  /mobile/read/{id}
    controller: App\Controller\NewsMobileController::readAction
    requirements:
       id: \d+

ap_newsmobile_search:
    path:  /mobile/search
    controller: App\Controller\NewsMobileController::searchAction

# Photo
ap_photomobile_index:
    path:  /mobile/photo/{page}/{theme}
    controller: App\Controller\PhotoMobileController::indexAction
    defaults:
        theme: null
    requirements:
       page: \d+
       theme: ".+"

ap_photomobile_selectthemeforindexphoto:
    path: /mobile/photo/selectThemeForIndexPhoto
    controller: App\Controller\PhotoMobileController::selectThemeForIndexPhotoAction

ap_photomobile_read:
    path:  /mobile/photo/read/{id}
    controller: App\Controller\PhotoMobileController::readAction
    requirements:
       id: \d+

# Testimony
ap_testimonymobile_index:
    path:  /mobile/testimony/{page}/{theme}
    controller: App\Controller\TestimonyMobileController::indexAction
    defaults:
        theme: null
    requirements:
       page: \d+
       theme: ".+"

ap_testimonymobile_selectthemeforindextestimony:
    path: /mobile/testimony/selectThemeForIndexTestimony
    controller: App\Controller\TestimonyMobileController::selectThemeForIndexTestimonyAction

ap_testimonymobile_read:
    path:  /mobile/testimony/read/{id}
    controller: App\Controller\TestimonyMobileController::readAction
    requirements:
       id: \d+

ap_testimonymobile_new:
    path:  /mobile/testimony/new
    controller: App\Controller\TestimonyMobileController::newAction

ap_testimonymobile_create:
    path:  /mobile/testimony/create
    controller: App\Controller\TestimonyMobileController::createAction

ap_testimonymobile_addfile:
    path:  /mobile/testimony/file/{id}
    controller: App\Controller\TestimonyMobileController::addFileAction

ap_testimonymobile_validatefile:
    path:  /mobile/testimony/validatefile
    controller: App\Controller\TestimonyMobileController::validateFileAction

# Witchcraft
ap_witchcraftmobile_index:
    path:  /mobile/witchcraft/{page}/{theme}
    controller: App\Controller\WitchcraftMobileController::indexAction
    defaults:
        theme: null
        page: 1
    requirements:
       page: \d+
       theme: ".+"

ap_witchcraftmobile_selectthemeforindexwitchcraft:
    path: /mobile/witchcraft/selectThemeForIndexWitchcraft
    controller: App\Controller\WitchcraftMobileController::selectThemeForIndexWitchcraftAction

ap_witchcraftmobile_read:
    path:  /mobile/witchcraft/read/{id}
    controller: App\Controller\WitchcraftMobileController::readAction
    requirements:
       id: \d+

ap_witchcraftmobile_new:
    path:  /mobile/witchcraft/new
    controller: App\Controller\WitchcraftMobileController::newAction

ap_witchcraftmobile_create:
    path:  /mobile/witchcraft/create
    controller: App\Controller\WitchcraftMobileController::createAction

ap_newsmobile_selectlanguage:
    path:  /mobile/selectlanguage/{language}
    controller: App\Controller\NewsMobileController::selectLanguageAction
    requirements:
       page: \d+

ap_pagemobile_page:
    path:  /mobile/page/{page}
    controller: App\Controller\NewsMobileController::pageAction