ClassifiedAds_Index:
    path:  /classifiedads/{page}/{idCategory}
    controller: App\Controller\ClassifiedAdsController::index
    defaults:
        page: 1
        idCategory: null
    requirements:
        page: \d+

ClassifiedAds_New:
    path:  /classifiedads/new
    controller: App\Controller\ClassifiedAdsController::newAction

ClassifiedAds_Read:
    path:  /classifiedads/read/{id}/{title_slug}
    controller: App\Controller\ClassifiedAdsController::read
    defaults:
        title_slug: null
    requirements:
        id: \d+

ClassifiedAds_MarkAs:
    path:  /classifiedads/markas/{id}
    controller: App\Controller\ClassifiedAdsController::markAs
    requirements:
        id: \d+

ClassifiedAds_Create:
    path:  /classifiedads/create
    controller: App\Controller\ClassifiedAdsController::create

ClassifiedAds_Validate:
    path:  /classifiedads/validate
    controller: App\Controller\ClassifiedAdsController::validate

ClassifiedAds_State:
    path:  /classifiedads/state/{id}/{state}
    controller: App\Controller\ClassifiedAdsController::state

# Administration
ClassifiedAdsCategory_Admin:
    resource: "routing/classifiedadscategoryadmin.yml"
    prefix:   /admin/classifiedadscategory

ClassifiedAds_Admin:
    resource: "routing/classifiedadsadmin.yml"
    prefix:   /admin/classifiedads