ClassifiedAds_Index:
    path:  /classifiedads/{page}
    controller: App\Controller\ClassifiedAdsController::index
    defaults:
        page: 1
    requirements:
        page: \d+

ClassifiedAds_New:
    path:  /classifiedads/new
    controller: App\Controller\ClassifiedAdsController::newAction

ClassifiedAds_Read:
    path:  /classifiedads/read/{id}/{title_slug}
    controller: App\Controller\ClassifiedAdsController::read
    requirements:
        id: \d+

ClassifiedAds_MarkAs:
    path:  /classifiedads/markas/{id}
    controller: App\Controller\ClassifiedAdsController::markAs
    requirements:
        id: \d+

ClassifiedAds_Create:
    path:  /classifiedads/create
    controller: App\Controller\ClassifiedAdsController::create

ClassifiedAds_Validate:
    path:  /classifiedads/validate
    controller: App\Controller\ClassifiedAdsController::validate

# Administration
ClassifiedAdsCategory_Admin:
    resource: "routing/classifiedadscategoryadmin.yml"
    prefix:   /admin/classifiedadscategory