Witchcraft_Index:
    path:  /grimoire/{page}
    controller: App\Controller\WitchcraftController::indexAction
    requirements:
        page: \d+
    defaults:
        page: 1

Witchcraft_TabGrimoire:
    path:  /grimoire/tab/{surtheme}/{id}/{theme}
    controller: App\Controller\WitchcraftController::tabGrimoireAction
    requirements:
       theme: ".+"
       id: \d+

Witchcraft_TabGrimoireDatatables:
    path: /tabgrimoiredatatables/{themeId}
    controller: App\Controller\WitchcraftController::tabGrimoireDatatablesAction

Witchcraft_Theme:
    path: /grimoire/theme/{id}
    controller: App\Controller\WitchcraftController::theme
    requirements:
       id: \d+

Witchcraft_ReadGrimoire:
    path:  /grimoire/read/{surtheme}/{id}/{title_slug}
    controller: App\Controller\WitchcraftController::readGrimoireAction
    requirements:
       surtheme: ".+"
       title_slug: .+

Witchcraft_ReadGrimoire_Simple:
    path:  /grimoire/read_simple/{id}/{title_slug}
    controller: App\Controller\WitchcraftController::readGrimoireSimple
    defaults:
        title_slug: null

Witchcraft_CountRitual:
    path:  /grimoire/count/{id}
    controller: App\Controller\WitchcraftController::countRitualAction
    requirements:
       id: \d+

Witchcraft_Pdfversion:
    path: /grimoire/pdfversion/{id}
    controller: App\Controller\WitchcraftController::pdfVersionAction

Witchcraft_New:
    path: /grimoire/new
    controller: App\Controller\WitchcraftController::newAction

Witchcraft_Create:
    path: /grimoire/create
    controller: App\Controller\WitchcraftController::createAction

Witchcraft_Waiting:
    path: /grimoire/waiting/{id}
    controller: App\Controller\WitchcraftController::waitingAction

Witchcraft_Validate:
    path: /grimoire/validate/{id}
    controller: App\Controller\WitchcraftController::validateAction

Witchcraft_World:
    path: /grimoire/world/{language}/{themeId}/{theme}
    controller: App\Controller\WitchcraftController::worldAction
    defaults:
        language: all
        themeId: 0
        theme: null
    requirements:
        theme: ".+"

Witchcraft_WorldDatatables:
    path: /grimoire/worlddatatables/{language}/{themeId}
    controller: App\Controller\WitchcraftController::worldDatatablesAction
    defaults:
        language: all
        themeId: 0

Witchcraft_SelectThemeForIndexWorld:
    path: /grimoire/selectThemeForIndexWorldAction/{language}
    controller: App\Controller\WitchcraftController::selectThemeForIndexWorldAction
    defaults:
        language: all

WitchcraftTool_Index:
    path: /witchcrafttool/{page}
    controller: App\Controller\WitchcraftController::indexWitchcraftToolAction
    defaults:
        page: 1
    requirements:
       page: \d+

WitchcraftTool_Show:
    path: /witchcrafttool/{id}/{title_slug}
    controller: App\Controller\WitchcraftController::showWitchcraftToolAction
    defaults:
        title_slug: null
    requirements:
       id: \d+

# Administration
SurThemeGrimoire_Admin:
    resource: "routing/surthemegrimoireadmin.yml"
    prefix:   /admin/theme_grimoire

Grimoire_admin:
    resource: "routing/grimoireadmin.yml"
    prefix:   /admin/grimoire

WitchcraftTool_admin:
    resource: "routing/witchcrafttooladmin.yml"
    prefix:   /admin/witchcrafttool

WitchcraftThemeTool_Admin:
    resource: "routing/witchcraftthemetooladmin.yml"
    prefix:   /admin/witchcraftthemetool