Book_Index:
    path: /book/{page}
    controller: App\Controller\BookController::indexAction
    defaults:
        page: 1
    requirements:
        page: \d+

Book_Show:
    path: /book/read/{id}/{title_slug}
    controller: App\Controller\BookController::showAction
    defaults:
        title_slug: null
    requirements:
        id: \d+
        title_slug: .+

Book_World:
    path: /book/world/{language}/{themeId}/{theme}
    controller: App\Controller\BookController::worldAction
    defaults:
        language: all
        themeId: 0
        theme: null
    requirements:
        theme: ".+"

Book_WorldDatatables:
    path: /book/worlddatatables/{language}/{themeId}
    controller: App\Controller\BookController::worldDatatablesAction
    defaults:
        language: all
        themeId: 0

Book_SelectThemeForIndexWorld:
    path: /book/selectThemeForIndexWorldAction/{language}
    controller: App\Controller\BookController::selectThemeForIndexWorldAction
    defaults:
        language: all

BookEdition_Save:
    path: /book/save/{id}/{title_slug}
    controller: App\Controller\BookController::saveAction

BookEdition_Download:
    path: /book/download/{id}
    controller: App\Controller\BookController::downloadAction

ByPublisherBook_Index:
    path: /book/bypublisher/{idPublisher}/{titlePublisher}/{page}
    controller: App\Controller\BookController::byPublisherAction
    defaults:
        page: 1
    requirements:
        idPublisher: \d+
        page: \d+

# Administration
Book_Admin:
    resource: "routing/bookadmin.yml"
    prefix:   /admin/book

BookEdition_Admin:
    resource: "routing/bookeditionadmin.yml"
    prefix:   /admin/bookedition

Publisher_Admin:
    resource: "routing/publisheradmin.yml"
    prefix:   /admin/publisher